- type: entity
  id: CellSequencerCircuitboard
  parent: BaseMachineCircuitboard
  name: cell sequencer machine board
  description: A machine printed circuit board for a cell sequencer.
  components:
  - type: Sprite
    state: science
  - type: MachineBoard
    prototype: CellSequencer
    stackRequirements:
      Plasma: 5
      MatterBin: 1
      Glass: 1
      Steel: 2
    tagRequirements:
      Dish:
        amount: 2
        defaultPrototype: PetriDish

- type: entity
  id: CellularFusionCircuitboard
  parent: BaseMachineCircuitboard
  name: cellular fusion machine board
  description: A machine printed circuit board for a cellular fusion.
  components:
  - type: Sprite
    state: science
  - type: MachineBoard
    prototype: CellularFusion
    stackRequirements:
      Plasma: 5
      MatterBin: 1
      Glass: 1
      Steel: 2
    tagRequirements:
      Dish:
        amount: 2
        defaultPrototype: PetriDish

- type: entity
  id: SlimeExtractorMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: slime extractor machine board
  description: A machine printed circuit board for a slime extractor.
  components:
  - type: Sprite
    state: medical
  - type: MachineBoard
    prototype: SlimeExtractor
    stackRequirements:
      # MatterBin: 2
      Manipulator: 1
      Steel: 5
    tagRequirements:
      Knife:
        amount: 2
        defaultPrototype: KitchenKnife
        examineName: construction-insert-info-examine-name-knife

- type: entity
  id: MiningServerCircuitboard
  parent: BaseMachineCircuitboard
  name: mining server board
  description: A machine printed circuit board for an mining server.
  components:
    - type: Sprite
      state: engineering
    - type: MachineBoard
      prototype: MiningServer
      stackRequirements:
        Cable: 5        
        Manipulator: 1

- type: entity
  id: WashingMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: washing machine board
  description: A machine printed circuit board for an washing machine.
  components:
    - type: Sprite
      state: service
    - type: MachineBoard
      prototype: WashingMachine
      stackRequirements:
        Manipulator: 1
        Glass: 2
        Cable: 2

- type: entity
  id: InjectorFabricatorMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: injector fabricator board
  description: A machine printed circuit board for an injector fabricator.
  components:
    - type: Sprite
      state: secmodschematic
    - type: MachineBoard
      prototype: InjectorFabricator
      stackRequirements:
        Manipulator: 2
        Glass: 5
        Cable: 2

- type: entity
  id: GoldprinterMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: gold printer board
  components:
  - type: MachineBoard
    prototype: Goldprinter
    stackRequirements:
      Manipulator: 2
      Glass: 5
      
- type: entity
  id: ExosuitFabricatorHyperConvectionMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: hyper convection exosuit fabricator board
  components:
  - type: Sprite
    state: science
  - type: MachineBoard
    prototype: ExosuitFabricatorHyperConvection
    stackRequirements:
      Manipulator: 4
      Glass: 5
    tagRequirements:
      Igniter:
        amount: 1
        defaultPrototype: Igniter
        
- type: entity
  id: BorgChargerTurboCircuitboard
  parent: BaseMachineCircuitboard
  name: cyborg recharging station machine board
  description: A machine printed circuit board for a robot recharging station.
  components:
    - type: Sprite
      sprite: Objects/Misc/module.rsi
      state: charger_APC
    - type: MachineBoard
      prototype: BorgChargerTurbo
      stackRequirements:
        Manipulator: 2
        CableMV: 5
    - type: PhysicalComposition
      materialComposition:
        Steel: 25
        Plastic: 25
    - type: StaticPrice
      price: 15