- type: entity
  parent: BaseItem
  id: FlowerRose
  name: rose
  description: "Something beautiful."
  components:
  - type: Clothing
    slots:
    - HEAD
    quickEquip: false
  - type: Sprite
    sprite: _Wega/Objects/Specific/Hydroponics/rose.rsi
    state: produce
  - type: Produce
    seedId: rose
  - type: PotencyVisuals
  - type: Appearance
  - type: Tag
    tags:
    - Rose
    - Flower

- type: entity
  parent: BaseItem
  id: FlowerSunflower
  name: sunflower
  description: "Yellow is bright, like stars in space."
  components:
  - type: Clothing
    slots:
    - HEAD
    quickEquip: false
  - type: Sprite
    sprite: _Wega/Objects/Specific/Hydroponics/sunflower.rsi
    state: produce
  - type: Produce
    seedId: sunflower
  - type: PotencyVisuals
  - type: Appearance
  - type: Tag
    tags:
    - Sunflower
    - Flower

- type: entity
  parent: BaseItem
  id: FlowerPeaceFlower
  name: peaceflower
  description: "Something beautiful."
  components:
  - type: Clothing
    slots:
    - HEAD
    quickEquip: false
  - type: Sprite
    sprite: _Wega/Objects/Specific/Hydroponics/peaceflower.rsi
    state: produce
  - type: Tag
    tags:
    - Peaceflower

- type: entity
  parent: BaseItem
  id: FlowerClown
  name: clown flower
  description: "Something terrible."
  components:
  - type: Clothing
    slots:
    - HEAD
    quickEquip: false
  - type: Sprite
    sprite: _Wega/Objects/Specific/Hydroponics/clownflower.rsi
    state: produce
  - type: Produce
    seedId: clownflower
  - type: PotencyVisuals
  - type: Appearance

- type: entity
  name: money cabbage
  description: "Money, money, MONEY!!"
  id: FoodMoneyCabbage
  parent: ProduceBase
  components:
  - type: Sprite
    sprite: _Wega/Objects/Specific/Hydroponics/moneycabbage.rsi
  - type: SolutionContainerManager
    solutions:
      food:
        reagents:
        - ReagentId: Monenium
          Quantity: 10
  - type: Item
    heldPrefix: produce
  - type: Produce
    seedId: moneyCabbage
    sound:
      path: /Audio/Effects/unwrap.ogg

- type: entity
  name: demonic watermelon
  parent: [FoodProduceBase, ItemHeftyBase]
  id: FoodDemonicWatermelon
  description: "Who would have thought that the main symbol of evil would be a watermelon?"
  components:
  - type: Item
    size: Small
    heldPrefix: produce
  - type: FlavorProfile
    flavors:
      - demonicwatermelon
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 25
        reagents:
        - ReagentId: Nutriment
          Quantity: 10
        - ReagentId: Vitamin
          Quantity: 5
        - ReagentId: Unholywater
          Quantity: 10
  - type: Sprite
    sprite: _Wega/Objects/Specific/Hydroponics/demonicwatermelon.rsi
  - type: Produce
    seedId: demonicWatermelon
  - type: Extractable
    juiceSolution:
      reagents:
      - ReagentId: DemonsBlood
        Quantity: 20
  - type: Damageable
    damageContainer: Biological
  - type: DamageOnHighSpeedImpact
    minimumSpeed: 0.1
    damage:
      types:
        Blunt: 1
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 1
      behaviors:
      - !type:PlaySoundBehavior
        sound:
          collection: desecration
      - !type:SpillBehavior
        solution: food
      - !type:DoActsBehavior
        acts: [ "Destruction" ]
  - type: SliceableFood
    count: 5
    slice: FoodDemonicWatermelonSlice
  - type: Butcherable
    butcheringType: Knife
    spawned:
    - id: ClothingHeadHatDemonicWatermelon
    - id: ClothingNeckWingsTail
  - type: Tag
    tags:
    - Fruit

- type: entity
  name: demonic watermelon slice
  parent: ProduceSliceBase
  id: FoodDemonicWatermelonSlice
  description: "A little piece of evil."
  components:
  - type: Item
    size: Tiny
  - type: FlavorProfile
    flavors:
      - demonicwatermelon
  - type: Sprite
    sprite: _Wega/Objects/Specific/Hydroponics/demonicwatermelon.rsi
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 5
        reagents:
        - ReagentId: Nutriment
          Quantity: 2
        - ReagentId: Vitamin
          Quantity: 1
        - ReagentId: Unholywater
          Quantity: 2
  - type: Extractable
    juiceSolution:
      reagents:
      - ReagentId: DemonsBlood
        Quantity: 4
  - type: Tag
    tags:
    - Fruit
    - Slice

- type: entity
  name: blue space banan
  parent: FoodProduceBase
  id: FoodBlueSpaceBanana
  description: "Weird blue banana"
  components:
  - type: Item
    heldPrefix: produce
  - type: FlavorProfile
    flavors:
      - banana
  - type: Edible
    trash:
    - TrashBlueSpaceBananaPeel
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 6
        reagents:
        - ReagentId: Nutriment
          Quantity: 4
        - ReagentId: Vitamin
          Quantity: 2
  - type: Sprite
    sprite: _Wega/Objects/Specific/Hydroponics/blue_space_banana.rsi
  - type: Produce
    seedId: blueSpaceBanana
  - type: Extractable
    juiceSolution:
      reagents:
      - ReagentId: JuiceBanana
        Quantity: 10
  - type: Tag
    tags:
    - Fruit

- type: entity
  name: blue space banana peel
  parent: BaseItem
  id: TrashBlueSpaceBananaPeel
  description: "The pinnacle of the art of humor."
  components:
    - type: Sprite
      sprite: _Wega/Objects/Specific/Hydroponics/blue_space_banana.rsi
      state: peel
    - type: Item
      sprite: _Wega/Objects/Specific/Hydroponics/blue_space_banana.rsi
      heldPrefix: peel
    - type: Slippery
      slipSound:
        path: "/Audio/Effects/teleport_arrival.ogg"
        params:
          volume: -5
    - type: StepTrigger
      intersectRatio: 0.2
    - type: CollisionWake
      enabled: false
    - type: Physics
      bodyType: Dynamic
    - type: Fixtures
      fixtures:
        slips:
          shape:
            !type:PhysShapeAabb
            bounds: "-0.2,-0.2,0.2,0.2"
          hard: false
          layer:
          - SlipLayer
        fix1:
          shape:
            !type:PhysShapeAabb
            bounds: "-0.2,-0.2,0.2,0.2"
          density: 30
          mask:
          - ItemMask
    - type: Tag
      tags:
      - Recyclable
      - Trash
      - BananaPeel
    - type: SolutionContainerManager
      solutions:
        food:
          maxVol: 10
          reagents:
          - ReagentId: PulpedBananaPeel
            Quantity: 10
    - type: Extractable
      grindableSolutionName: food
    - type: SpaceGarbage
    - type: TriggerOnSlip
    - type: SpawnOnTrigger
      proto: PortalBsBanan

- type: entity
  name: glowing berries
  parent: FoodProduceBase
  id: FoodRadioactiveBerries
  description: "They look so delicious! But for some reason it's hard to look at them."
  components:
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 10
        reagents:
        - ReagentId: Radium
          Quantity: 5
        - ReagentId: Uranium
          Quantity: 5
  - type: Sprite
    sprite: _Wega/Objects/Specific/Hydroponics/radioactive_berry.rsi
  - type: Produce
    seedId: radioactiveBerries
  - type: Extractable
    juiceSolution:
      reagents:
      - ReagentId: NuclearCola
        Quantity: 10
  - type: Tag
    tags:
    - Fruit
  - type: RadiationSource
    intensity: 0.3
    slope: 0.1
  - type: PointLight
    color: "#19FF19FF"
    energy: 2.5
    radius: 1.5
    softness: 1

- type: entity
  name: alien berries
  parent: FoodProduceBase
  id: FoodAlienBerries
  description: "They look like very small pieces of alien artifacts."
  components:
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 5
        reagents:
        - ReagentId: Artifexium
          Quantity: 5
  - type: Sprite
    sprite: _Wega/Objects/Specific/Hydroponics/alien_berry.rsi
  - type: Produce
    seedId: alienBerries
  - type: Extractable
    juiceSolution:
      reagents:
      - ReagentId: Singulo
        Quantity: 10
  - type: Tag
    tags:
    - AlienBerries
    - Fruit

- type: entity
  name: energy potato
  parent: FoodProduceBase
  id: FoodEnergyPotato
  description: "Potatoes with a huge amount of nutrients!"
  components:
  - type: Item
    heldPrefix: produce
  - type: FlavorProfile
    flavors:
      - Potato
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 24
        reagents:
        - ReagentId: Nutriment
          Quantity: 9
        - ReagentId: Licoxide
          Quantity: 15
  - type: Sprite
    sprite: _Wega/Objects/Specific/Hydroponics/energy_potato.rsi
  - type: Produce
    seedId: energyPotato
  - type: Extractable
    juiceSolution:
      reagents:
      - ReagentId: JuicePotato
        Quantity: 20
  - type: Tag
    tags:
    - SuperPotato
    - Potato
    - Vegetable

- type: entity
  name: tea tree branch
  description: "The most aromatic part of this plant is not the leaves, but the branches!"
  id: BranchTreeTeaPlant
  parent: ProduceBase
  components:
  - type: Sprite
    sprite: _Wega/Objects/Specific/Hydroponics/relaxing_tea.rsi
  - type: SolutionContainerManager
    solutions:
      food:
        reagents:
        - ReagentId: RelaxingTeaAdust
          Quantity: 10
  - type: Produce
    seedId: treeTeaPlant

- type: entity
  name: invisible grapes
  parent: FoodProduceBase
  id: FoodInvisibleGrape
  description: "Barely noticeable grapes."
  components:
  - type: Item
    heldPrefix: produce
  - type: FlavorProfile
    flavors:
      - grape
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 4
        reagents:
        - ReagentId: GrapeJuiceInvisible
          Quantity: 2
        - ReagentId: Nothing
          Quantity: 2
  - type: Sprite
    sprite: _Wega/Objects/Specific/Hydroponics/Invisiblgrape.rsi
  - type: Produce
    seedId: invisibleGrape
  - type: Extractable
    juiceSolution:
      reagents:
      - ReagentId: GrapeJuiceInvisible
        Quantity: 5
  - type: Tag
    tags:
    - Fruit

- type: entity
  name: lollipop 
  parent: FoodProduceBase
  id: FoodProduceLollipop
  description: "the most delicious lollipops!"
  components:
  - type: FlavorProfile
    flavors:
      - sweet
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 5
        reagents:
        - ReagentId: Sugar
          Quantity: 4
        - ReagentId: Vitamin
          Quantity: 1
  - type: Sprite
    sprite: _Wega/Objects/Specific/Hydroponics/candytree.rsi
  - type: Produce
    seedId: candytree
  - type: SpawnItemsOnUse
    items:
      - id: FoodProduceLollipopBar
    sound:
      path: /Audio/Effects/unwrap.ogg
  - type: Tag
    tags:
    - Lollipops

- type: entity
  name: lollipop 
  parent: FoodProduceBase
  id: FoodProduceLollipopRandom
  suffix: "random chemicals"
  description: "the most delicious lollipops and more!"
  components:
  - type: FlavorProfile
    flavors:
      - sweet
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 5
        reagents:
        - ReagentId: Sugar
          Quantity: 4
        - ReagentId: UnstableMutagen
          Quantity: 1
  - type: Sprite
    sprite: _Wega/Objects/Specific/Hydroponics/candytreerandom.rsi
  - type: Produce
    seedId: candytreerandom
  - type: SpawnItemsOnUse
    items:
      - id: FoodProduceLollipopRandomBar
    sound:
      path: /Audio/Effects/unwrap.ogg
  - type: Tag
    tags:
    - Lollipops

- type: entity
  name: lollipop 
  parent: FoodProduceBase
  id: FoodProduceLollipopMedical
  suffix: "medical chemicals"
  description: "the most delicious lollipops and more!"
  components:
  - type: FlavorProfile
    flavors:
      - sweet
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 5
        reagents:
        - ReagentId: Sugar
          Quantity: 4
        - ReagentId: UnstableMutagen
          Quantity: 1
  - type: Sprite
    sprite: _Wega/Objects/Specific/Hydroponics/candytreerandom.rsi
  - type: SpawnItemsOnUse
    items:
      - id: FoodProduceLollipopMedicalBar
    sound:
      path: /Audio/Effects/unwrap.ogg
  - type: Tag
    tags:
    - Lollipops

- type: entity
  name: lollipop 
  parent: FoodProduceBase
  id: FoodProduceLollipopMedRandom
  suffix: "medical case"
  description: "the most delicious lollipops and more!"
  components:
  - type: FlavorProfile
    flavors:
      - sweet
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 5
        reagents:
        - ReagentId: Sugar
          Quantity: 4
        - ReagentId: UnstableMutagen
          Quantity: 1
  - type: Sprite
    sprite: _Wega/Objects/Specific/Hydroponics/candytreerandom.rsi
  - type: SpawnItemsOnUse
    items:
      - id: FoodProduceLollipopBar
        orGroup: CCandyBorg
      - id: FoodProduceLollipopMedicalBar
        prob: 0.5
        orGroup: CCandyBorg
    sound:
      path: /Audio/Effects/unwrap.ogg
  - type: Tag
    tags:
    - Lollipops

- type: entity
  name: tangerine
  parent: FoodProduceBase
  id: FoodProduceTangerine
  description: "the best New Year's food!"
  components:
  - type: FlavorProfile
    flavors:
      - tangerine
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 5
        reagents:
        - ReagentId: Nutriment
          Quantity: 3
        - ReagentId: Vitamin
          Quantity: 2
  - type: Extractable
    juiceSolution:
      reagents:
      - ReagentId: JuiceTangerine
        Quantity: 7.5
  - type: Sprite
    sprite: _Wega/Objects/Specific/Hydroponics/tangerine.rsi
  - type: Produce
    seedId: tangerine
  - type: SpawnItemsOnUse
    items:
      - id: FoodProduceTangerineTrash
      - id: FoodProduceTangerineOpen
    sound:
      path: /Audio/Effects/packetrip.ogg
  - type: Tag
    tags:
    - Fruit

- type: entity
  name: tangerine open
  parent: FoodProduceBase
  id: FoodProduceTangerineOpen
  description: "the best New Year's food!"
  components:
  - type: FlavorProfile
    flavors:
      - tangerine
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 5
        reagents:
        - ReagentId: Nutriment
          Quantity: 3
        - ReagentId: Vitamin
          Quantity: 2
  - type: Extractable
    juiceSolution:
      reagents:
      - ReagentId: JuiceTangerine
        Quantity: 7.5
  - type: Sprite
    sprite: _Wega/Objects/Specific/Hydroponics/tangerine.rsi
    state: open
  - type: Tag
    tags:
    - Fruit

- type: entity
  parent: BaseItem
  name: tangerine peel
  id: FoodProduceTangerineTrash
  description: It smells strongly of tangerine!
  components:
  - type: Sprite
    sprite: _Wega/Objects/Specific/Hydroponics/tangerine.rsi
    state: trash
  - type: FlavorProfile
    flavors:
      - tangerine
  - type: Item
    size: Tiny
  - type: Tag
    tags:
    - Trash
  - type: SpaceGarbage
  - type: StaticPrice
    price: 0
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 7
        reagents:
        - ReagentId: Vitamin
          Quantity: 7
  - type: Edible
    requiresSpecialDigestion: true
  - type: Extractable
    grindableSolutionName: food

- type: entity
  name: festive tangerine
  parent: FoodProduceBase
  id: FoodProduceFestiveTangerine
  description: "A beautiful box with a gift!"
  components:
  - type: FlavorProfile
    flavors:
      - tangerine
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 5
        reagents:
        - ReagentId: Nutriment
          Quantity: 3
        - ReagentId: Vitamin
          Quantity: 2
  - type: Sprite
    sprite: _Wega/Objects/Specific/Hydroponics/festive_tangerine.rsi
  - type: Produce
    seedId: festivetangerine
  - type: SpawnItemsOnUse
    items:
      - id: FoodProduceFestiveTangerineTrash
      - id: Bucket
        orGroup: GiftPool
      - id: PlushieGhost
        orGroup: GiftPool
      - id: PlushieBee
        orGroup: GiftPool
      - id: PlushieRGBee
        orGroup: GiftPool
      - id: PlushieNuke
        orGroup: GiftPool
      - id: PlushieRouny
        orGroup: GiftPool
      - id: PlushieLizard #Weh!
        orGroup: GiftPool
      - id: PlushieRainbowLizard
        orGroup: GiftPool
      - id: PlushieNar
        orGroup: GiftPool
      - id: PlushieCarp
        orGroup: GiftPool
      - id: PlushieMagicarp
        orGroup: GiftPool
      - id: PlushieHolocarp
        orGroup: GiftPool
      - id: PlushieRainbowCarp
        orGroup: GiftPool
      - id: PlushieSlime
        orGroup: GiftPool
      - id: PlushieSnake
        orGroup: GiftPool
      - id: PlushieVox
        orGroup: GiftPool
      - id: PlushieRatvar
        orGroup: GiftPool
      - id: PlushieSpaceLizard
        orGroup: GiftPool
      - id: PlushieSharkBlue
        orGroup: GiftPool
      - id: PlushieSharkPink
        orGroup: GiftPool
      - id: PlushieSharkGrey
        orGroup: GiftPool
      - id: ToyAmongPequeno
        orGroup: GiftPool
      - id: PlushieDiona
        orGroup: GiftPool
      - id: PlushieArachind
        orGroup: GiftPool
      - id: ToyMouse
        orGroup: GiftPool
      - id: ToyAi
        orGroup: GiftPool
      - id: ToyNuke
        orGroup: GiftPool
      - id: ToyFigurinePassenger
        orGroup: GiftPool
      - id: ToyFigurineGriffin
        orGroup: GiftPool
      - id: ToyHonk
        orGroup: GiftPool
      - id: ToyIan
        orGroup: GiftPool
      - id: ToyMarauder
        orGroup: GiftPool
      - id: ToyMauler
        orGroup: GiftPool
      - id: ToyGygax
        orGroup: GiftPool
      - id: ToyOdysseus
        orGroup: GiftPool
      - id: ToyFigurineOwlman
        orGroup: GiftPool
      - id: ToyDeathRipley
        orGroup: GiftPool
      - id: ToyPhazon
        orGroup: GiftPool
      - id: ToyFireRipley
        orGroup: GiftPool
      - id: ToyReticence
        orGroup: GiftPool
      - id: ToyRipley
        orGroup: GiftPool
      - id: ToySeraph
        orGroup: GiftPool
      - id: ToyDurand
        orGroup: GiftPool
      - id: ToyFigurineSkeleton
        orGroup: GiftPool
      - id: FoamBlade
        orGroup: GiftPool
      - id: PonderingOrb
        orGroup: GiftPool
      - id: Skub
        orGroup: GiftPool
      - id: PersonalAI
        orGroup: GiftPool
      - id: DiceBag
        orGroup: GiftPool
      - id: CrayonBox
        orGroup: GiftPool
      - id: ToySword
        orGroup: GiftPool
      - id: Coal1
        orGroup: GiftPool
      - id: ToyRubberDuck
        orGroup: GiftPool
      - id: RGBStaff
        orGroup: GiftPool
    sound:
      path: /Audio/Effects/packetrip.ogg
  - type: Tag
    tags:
    - Fruit

- type: entity
  name: gift wrapping
  parent: BaseItem
  id: FoodProduceFestiveTangerineTrash
  description: This is rubbish.
  components:
  - type: Sprite
    sprite: _Wega/Objects/Specific/Hydroponics/festive_tangerine.rsi
    state: trash
  - type: Item
    size: Tiny
  - type: Tag
    tags:
    - Trash
  - type: PhysicalComposition
    materialComposition:
      Plastic: 100
  - type: SpaceGarbage
  - type: StaticPrice
    price: 0
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 10
        reagents:
        - ReagentId: ToxinTrash
          Quantity: 5
  - type: Edible
    requiresSpecialDigestion: true
